#!/bin/sh
### BEGIN INIT INFO
# Provides:          motd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: show the raspi image on a nokia5110 lcd display
# Description:       shows a picture named bootimage.bmp from same directory
#                    where image.py is stored on an LCD display of type Nokia 5110
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

do_start () {
	# show boot picture
	cd /opt/startup
	python image.py &
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  *)
	echo "Usage: motd [start|stop]" >&2
	exit 3
	;;
esac

:
